export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_ATTEMPT_SUCCESS = "LOGIN_ATTEMPT_SUCCESS";
export const LOGIN_ATTEMPT_FAIL = "LOGIN_ATTEMPT_FAIL";
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
